#!/bin/bash

touch '*\\'"Best School"\'\\*$\?\*\*\*\*\*:)     # create the file
echo "Best School" > '*\\'"Best School"\'\\*$\?\*\*\*\*\*:'    # add text to the file
echo "" >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:'
