#!/usr/bin/env bash
#Install haproxy and configurate both servers
apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 382976-web-01  100.25.179.61:80 check\n\tserver 382976-web-01  18.207.140.4:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
