#!/usr/bin/env bash
#Process and PID file

terminate() {
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && terminate' SIGTERM
    trap 'terminate' SIGQUIT
done
