#!/usr/bin/env bash
#loops from 1-10, displays various messages on luck, otherwise "Best School

count=0

while [ $count -ne 10 ]
do
    if [ $count -eq 3 ]
    then
	echo "bad luck"
    elif [ $count -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( count++ ))
done
