#!/usr/bin/env bash
#configures localhost and Facebook to point to a different address

cp /etc/hosts ~/hosts.alter
echo "127.0.0.2    localhost" > ~/hosts.alter
echo "8.8.8.8      facebook.com" >> ~/hosts.alter
cp -f ~/hosts.alter /etc/hosts
